### ISSUE TITLE
Script breaks when it can't find the index

### ISSUE THREAD

**Issue by derricksong** [Incapsula/logs-downloader#27]
Logs in the screenshot.  I tried restarting the service and it's still looking for logs based on the "Last Known Downloaded ID" but it will inevitably break again when it gets to the part of its logic where it's looking for the index file.

![image](https://user-images.githubusercontent.com/11879205/58909348-bd0efa00-86c7-11e9-913c-0bc68e7acc31.png)

**Comment by DoronLehmann** [comment]
Hi,
There should always be an index file.
I suggest that you manually try to download the index file (via browser/wget/etc.).
If you will still get a 404 response, I suggest that you will open a support ticket to Imperva, since it is most likely an issue which is not related to the downloader script.

**Comment by OmerLitov** [comment]
Hi, this repository is deprecated.
please download the script from https://github.com/imperva/incapsula-logs-downloader
